##################################################
## Project: DGRPool
## Script purpose: Plotting phenotype-phenotype correlation heatmap
## Version: 1.0.0
## Date Created: 2022 Dec 12
## Date Modified: 2024 Jul 18
## Author: Vincent Gardeux (vincent.gardeux@epfl.ch)
##################################################

# Libraries
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(ggplot2))

## Load Spearman correlation data
data.correlation_spearman <- fread("../resources/phenotype_correlation_spearman.tsv", header = T, sep = "\t", data.table = F) # Generated by previous script
rownames(data.correlation_spearman) <- data.correlation_spearman[,1]
data.correlation_spearman <- data.correlation_spearman[,-1]

## Order samples by study
sample_studies <- limma::strsplit2(colnames(data.correlation_spearman), "_")[,1]
studies_ordered <- unique(sample_studies) # It is ordered by the previous script
samples_ordered <- colnames(data.correlation_spearman) # It is ordered by the previous script
xpos <- cumsum(table(sample_studies)[studies_ordered])
data.annot_studies <- data.frame(Study = sample_studies)
rownames(data.annot_studies) <- samples_ordered

## Find curated studies
phenotypes_information <- fread("../resources/phenotypes.tsv", data.table = F)
phenotypes_information <- phenotypes_information[,c("study_id", "study_name", "study_status")]
phenotypes_information <- phenotypes_information[!duplicated(phenotypes_information),]
phenotypes_information$study_name <- paste0("(",phenotypes_information$study_name,")")
rownames(phenotypes_information) <- paste0("S", phenotypes_information$study_id)
curated.studies.names <- paste0("S", sort(phenotypes_information$study_id[phenotypes_information$study_status == "integrated"]))
phenotypes_information <- phenotypes_information[curated.studies.names,]

## Subset data for curated studies
curated.studies <- subset(data.annot_studies, Study %in% curated.studies.names) 
xpos_curated <- cumsum(table(curated.studies$Study)[curated.studies.names])

## Help for the final figure caption
fwrite(phenotypes_information, "legend.heatmap.curated.txt", sep = "\t", row.names = T, col.names = T, quote = F)

## Draw Spearman's correlation heatmap, all, no thresholding
data.heatmap <- data.correlation_spearman
data.heatmap[lower.tri(data.heatmap)] <- NA

pdf("correlation_heatmap_spearman_curated.pdf", width = 20, height = 20)
pheatmap(data.heatmap[row.names(curated.studies), row.names(curated.studies)], legend = T, annotation_legend = F, gaps_col = xpos_curated[unique(curated.studies$Study)], gaps_row=xpos_curated[unique(curated.studies$Study)], annotation_col = data.annot_studies, annotation_names_col = F, annotation_row = data.annot_studies, annotation_names_row = F, color = colorRampPalette(c("blue", "white", "red"))(100), show_rownames = F, show_colnames = F, cluster_rows=F, cluster_cols=F, na_col="white", border_color ="white")
dev.off()
