create table users(
-- generated by devise
);

create table journals(
id serial,
name text,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table statuses(
id serial,
name text, -- submitted, validated, rejected, integrated
css_class text
);

create table studies(
id serial,
title text,
authors text,
abstract text,
journal_id int references journals,
pmid int,
doi text,
created_at timestamp,
updated_at timestamp,
status_id int references statuses,
submitter_id int references users,
validator_id int references users,
primary key (id)
);

create index studies_pmid_idx on studies(pmid);
create index studies_doi_idx on studies(doi);

create table categories(
id serial,
name text,
description text,
user_id int references users,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table categories_studies(
category_id int references categories,
study_id int references studies
);

create table phenotype_keywords(
id serial,
name text,
user_id int references users,
created_at timestamp,
updated_at timestamp,
primary key (id)
);


create table genes( --ensembl_genes
id serial
-- copy table from asap for Flybase genes
primary key (id)
);

create table dgrp_lines(
id serial,
name text,
user_id int references users,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table dgrp_line_genes( -- to confirm
id serial,
dgrp_line_id int references dgrp_lines,
gene_id int references genes,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table dgrp_line_studies(
id serial,
dgrp_line_id int references dgrp_lines,
study_id int references studies,
user_id int references users,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table dgrp_line_studies_phenotype_keywords(
dgrp_line_study_id int references dgrp_line_studies,
phenotype_keyword_id int references phenotype_keywords
);

create table ontologies( -- FBcv, FBbt, etc...
id serial
name text,
tag text,
file_url text, --file url (obo if exists)
format text,
latest_version text, --name or timestamp
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table ontology_terms(
id serial,
ontology_id int references ontologies,
identifier text,
alt_identifiers text,
name text,
description text,
content_json text,
obsolete bool default false,
latest_version text, -- to keep track if it becomes obsolete
related_gene_ids text,
related_pmids text, -- or related_study_ids if we plan to add automatically all the papers that are referenced in the termsthat we map to a given phenotype
node_gene_ids text,
node_term_ids text,
parent_term_ids text,
children_term_ids text,
lineage text,
original bool,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table phenotypes(
id serial,
name text,
description text,
user_id int references users,
created_at timestamp,
updated_at timestamp,
primary key (id)
);

create table dgrp_line_studies_phenotypes(
dgrp_line_study_id int references dgrp_line_studies,
phenotype_id int references phenotypes
);

create table ontology_terms_phenotypes(
ontology_term_id int references ontology_terms,
phenotype_id int references phenotypes
);

